---

- name: Java - create package directory
  file: path=/home/ubuntu/packages state=directory mode=0777 owner=ubuntu group=ubuntu

- name: Java - download package
  get_url:
    headers: "Cookie: oraclelicense=accept-securebackup-cookie"
    url: http://download.oracle.com/otn-pub/java/jdk/8u144-b01/090f390dda5b47b9b721c7dfaa008135/jdk-8u144-linux-x64.tar.gz
    dest: /home/ubuntu/packages
    mode: 0755

- name: Java - download JCE
  get_url:
    headers: "Cookie: oraclelicense=accept-securebackup-cookie"
    url: http://download.oracle.com/otn-pub/java/jce/8/jce_policy-8.zip
    dest: /tmp
    mode: 0755
  ignore_errors: true

# Install Java

- name: Java - create root directory
  file: path=/opt/jdk state=directory mode=0755 owner=root group=root
  when: training_solution

- name: Java - install package
  unarchive: src=/home/ubuntu/packages/jdk-8u144-linux-x64.tar.gz dest=/opt/jdk
  when: training_solution

- name: Java - set alternative for java
  command: "update-alternatives --install /usr/bin/java java /opt/jdk/jdk1.8.0_144/bin/java 100"
  when: training_solution

- name: Java - set alternative for javac
  command: "update-alternatives --install /usr/bin/javac javac /opt/jdk/jdk1.8.0_144/bin/javac 100"
  when: training_solution
  
- name: Java - set JAVA_HOME
  lineinfile: dest=/etc/environment regexp="^JAVA_HOME=" line="JAVA_HOME=/opt/jdk/jdk1.8.0_144"
  when: training_solution
  
# Install JCE

- name: Java - install unzip
  apt: name=unzip state=present

- name: Java - unzip JCE
  unarchive: src=/tmp/jce_policy-8.zip dest=/tmp
  when: training_solution
  
- name: Java - copy local policy
  command: "cp /tmp/UnlimitedJCEPolicyJDK8/local_policy.jar /opt/jdk/jdk1.8.0_144/jre/lib/security/local_policy.jar"
  when: training_solution

- name: Java - copy US export policy
  command: "cp /tmp/UnlimitedJCEPolicyJDK8/US_export_policy.jar /opt/jdk/jdk1.8.0_144/jre/lib/security/US_export_policy.jar"
  when: training_solution
